package com.microllm.model;
import com.microllm.layers.MultiHeadAttention;import com.microllm.tensor.*;import java.util.*;
/** Causal-attention language model. Attention is trained over complete windows; FFN is a zero residual for this milestone. */
public final class Transformer{
 private final ModelConfig c;private final Tensor token,pos,finalNorm,out;private final Tensor[]w;
 public Transformer(ModelConfig c,long seed){this.c=c;Random r=new Random(seed);token=Tensor.randomNormal(r,.02,c.vocabSize(),c.dModel());pos=Tensor.randomNormal(r,.02,c.maxSeqLen(),c.dModel());finalNorm=Tensor.ones(c.dModel());out=Tensor.randomNormal(r,.02,c.dModel(),c.vocabSize());w=new Tensor[c.nLayers()*8];for(int l=0;l<c.nLayers();l++){int b=l*8;w[b]=Tensor.ones(c.dModel());for(int i=1;i<=4;i++)w[b+i]=Tensor.randomNormal(r,.02,c.dModel(),c.dModel());w[b+5]=Tensor.ones(c.dModel());w[b+6]=Tensor.zeros(c.dModel(),c.dFfn());w[b+7]=Tensor.zeros(c.dFfn(),c.dModel());}}
 public ModelConfig config(){return c;}public Tensor tokenEmbedding(){return token;}public Tensor positionEmbedding(){return pos;}public Tensor finalNorm(){return finalNorm;}public Tensor output(){return out;}public Tensor layerWeight(int i){return w[i];}
 public List<Tensor> trainableParameters(){var p=new ArrayList<Tensor>(List.of(token,pos,out));for(int l=0;l<c.nLayers();l++){int b=l*8;p.add(w[b+1]);p.add(w[b+2]);p.add(w[b+3]);p.add(w[b+4]);}return p;}
 public double trainStep(int input,int position,int target){return trainWindow(new int[]{input},new int[]{target},position);}
 public double trainWindow(int[] input,int[] target,int start){if(input.length==0||input.length!=target.length||input.length>c.maxSeqLen())throw new IllegalArgumentException("invalid window");int n=input.length,d=c.dModel(),v=c.vocabSize();double[][]x=new double[n][d];for(int p=0;p<n;p++)for(int i=0;i<d;i++)x[p][i]=token.get(input[p]*d+i)+pos.get(((start+p)%c.maxSeqLen())*d+i);double[][]before=x;var caches=new MultiHeadAttention.Cache[c.nLayers()];for(int l=0;l<c.nLayers();l++){int b=l*8;double[][]norm=new double[n][d];for(int p=0;p<n;p++)norm[p]=rms(x[p],w[b]);var a=new MultiHeadAttention(d,c.nHeads(),w[b+1].values(),w[b+2].values(),w[b+3].values(),w[b+4].values());caches[l]=a.forward(norm);double[][]next=new double[n][d];for(int p=0;p<n;p++)for(int i=0;i<d;i++)next[p][i]=x[p][i]+caches[l].output()[p][i];x=next;}
 double loss=0;double[][]gx=new double[n][d];for(int p=0;p<n;p++){double[]z=rms(x[p],finalNorm),prob=Ops.softmax(row(z,out,d,v));loss-=Math.log(Math.max(prob[target[p]],1e-12));prob[target[p]]-=1;double[]gn=new double[d];for(int i=0;i<d;i++)for(int j=0;j<v;j++){out.gradient()[i*v+j]+=z[i]*prob[j];gn[i]+=out.get(i*v+j)*prob[j];}gx[p]=rmsBack(gn,x[p],finalNorm);}
 for(int l=c.nLayers()-1;l>=0;l--){int b=l*8;var a=new MultiHeadAttention(d,c.nHeads(),w[b+1].values(),w[b+2].values(),w[b+3].values(),w[b+4].values());var g=a.backward(caches[l],gx);add(w[b+1].gradient(),g.q());add(w[b+2].gradient(),g.k());add(w[b+3].gradient(),g.v());add(w[b+4].gradient(),g.o());double[][]next=new double[n][d];for(int p=0;p<n;p++)next[p]=rmsBack(g.input()[p],before[p],w[b]);gx=next;}
 for(int p=0;p<n;p++)for(int i=0;i<d;i++){token.gradient()[input[p]*d+i]+=gx[p][i];pos.gradient()[((start+p)%c.maxSeqLen())*d+i]+=gx[p][i];}return loss/n;}
 private double[]rms(double[]x,Tensor s){double q=0;for(double z:x)q+=z*z;double inv=1/Math.sqrt(q/x.length+c.rmsNormEpsilon());double[]y=new double[x.length];for(int i=0;i<x.length;i++)y[i]=x[i]*inv*s.get(i);return y;}private double[]rmsBack(double[]g,double[]x,Tensor s){double q=0,dot=0;for(int i=0;i<x.length;i++){q+=x[i]*x[i];dot+=g[i]*s.get(i)*x[i];}double inv=1/Math.sqrt(q/x.length+c.rmsNormEpsilon());double[]y=new double[x.length];for(int i=0;i<x.length;i++)y[i]=inv*g[i]*s.get(i)-x[i]*dot*inv*inv*inv/x.length;return y;}private static double[]row(double[]x,Tensor m,int r,int col){double[]y=new double[col];for(int i=0;i<r;i++)for(int j=0;j<col;j++)y[j]+=x[i]*m.get(i*col+j);return y;}private static void add(double[]a,double[]b){for(int i=0;i<a.length;i++)a[i]+=b[i];}
}
