package com.microllm.layers;

/** Causal multi-head attention math, including gradients for all four projections.
 * Matrices are row-major [inputDimension, outputDimension], matching Go. */
public final class MultiHeadAttention {
    private final int width, heads, headWidth; private final double[] qWeight,kWeight,vWeight,oWeight;
    public MultiHeadAttention(int width,int heads,double[] q,double[] k,double[] v,double[] o){if(width%heads!=0)throw new IllegalArgumentException("width must divide heads");this.width=width;this.heads=heads;headWidth=width/heads;qWeight=q;kWeight=k;vWeight=v;oWeight=o;}
    public Cache forward(double[][] input){int n=input.length;double[][]q=new double[n][],k=new double[n][],v=new double[n][],joined=new double[n][],output=new double[n][];double[][][] probabilities=new double[n][heads][];for(int p=0;p<n;p++){q[p]=rowMat(input[p],qWeight,width,width);k[p]=rowMat(input[p],kWeight,width,width);v[p]=rowMat(input[p],vWeight,width,width);joined[p]=new double[width];for(int h=0;h<heads;h++){double[] a=new double[p+1];for(int t=0;t<=p;t++){for(int d=0;d<headWidth;d++)a[t]+=q[p][h*headWidth+d]*k[t][h*headWidth+d];a[t]/=Math.sqrt(headWidth);}softmax(a);probabilities[p][h]=a;for(int t=0;t<=p;t++)for(int d=0;d<headWidth;d++)joined[p][h*headWidth+d]+=a[t]*v[t][h*headWidth+d];}output[p]=rowMat(joined[p],oWeight,width,width);}return new Cache(input,q,k,v,joined,probabilities,output);}
    public Gradients backward(Cache c,double[][] gradOutput){int n=c.input.length;double[][]gInput=new double[n][width],gQ=new double[n][width],gK=new double[n][width],gV=new double[n][width];double[]gq=new double[width*width],gk=new double[width*width],gv=new double[width*width],go=new double[width*width];for(int p=0;p<n;p++){double[]gJoined=new double[width];for(int i=0;i<width;i++)for(int j=0;j<width;j++){go[i*width+j]+=c.joined[p][i]*gradOutput[p][j];gJoined[i]+=oWeight[i*width+j]*gradOutput[p][j];}for(int h=0;h<heads;h++){double[]ga=new double[p+1];for(int t=0;t<=p;t++)for(int d=0;d<headWidth;d++){int z=h*headWidth+d;ga[t]+=gJoined[z]*c.v[t][z];gV[t][z]+=c.probabilities[p][h][t]*gJoined[z];}double mean=0;for(int t=0;t<=p;t++)mean+=ga[t]*c.probabilities[p][h][t];for(int t=0;t<=p;t++){double gs=c.probabilities[p][h][t]*(ga[t]-mean)/Math.sqrt(headWidth);for(int d=0;d<headWidth;d++){int z=h*headWidth+d;gQ[p][z]+=gs*c.k[t][z];gK[t][z]+=gs*c.q[p][z];}}} }for(int p=0;p<n;p++)for(int i=0;i<width;i++)for(int j=0;j<width;j++){gq[i*width+j]+=c.input[p][i]*gQ[p][j];gk[i*width+j]+=c.input[p][i]*gK[p][j];gv[i*width+j]+=c.input[p][i]*gV[p][j];gInput[p][i]+=qWeight[i*width+j]*gQ[p][j]+kWeight[i*width+j]*gK[p][j]+vWeight[i*width+j]*gV[p][j];}return new Gradients(gInput,gq,gk,gv,go);}
    private static double[]rowMat(double[]x,double[]w,int r,int c){double[]y=new double[c];for(int i=0;i<r;i++)for(int j=0;j<c;j++)y[j]+=x[i]*w[i*c+j];return y;}private static void softmax(double[]x){double max=Double.NEGATIVE_INFINITY;for(double z:x)max=Math.max(max,z);double sum=0;for(int i=0;i<x.length;i++){x[i]=Math.exp(x[i]-max);sum+=x[i];}for(int i=0;i<x.length;i++)x[i]/=sum;}
    public record Cache(double[][] input,double[][] q,double[][] k,double[][] v,double[][] joined,double[][][] probabilities,double[][] output){} public record Gradients(double[][] input,double[] q,double[] k,double[] v,double[] o){}
}
